---
deployment:
  tasks:
    - export DEPLOYPATH=/home/islx3544/public_html/sistem/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
